# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 firecat2d developers

name: Emscripten

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      env:
        EMSCRIPTEN_ROOT: "/usr/lib/emscripten"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pacman -Syu --noconfirm cmake make git pkgconf emscripten ninja pnpm

      - name: Configure CMake
        run: cmake --preset dev_wasm

      - name: Build
        run: cmake --build build_wasm --config Release

      - name: Install pnpm packages
        run: pnpm install
        working-directory: examples

      - name: Build client
        run: pnpm build
        working-directory: examples/

      - name: Setup Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./examples/dist"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v4
