# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 firecat2d developers

name: Ubuntu

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04]
        c_compiler: [clang]
        include:
          - os: ubuntu-26.04
            c_compiler: clang
            cpp_compiler: clang++
    env:
      CC: clang
      CXX: clang++

    steps:
      - uses: actions/checkout@v7

      - name: Install Dependencies
        run: |
          sudo apt -y update

          sudo apt -y install build-essential git make \
          pkg-config cmake ninja-build sccache lld \
          libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libsdl3-dev libfontconfig-dev

      - name: Setup sccache
        uses: hendrikmuhs/ccache-action@v1.2.23
        with:
          create-symlink: true
          variant: sccache
          update-package-index: false
          key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.c_compiler }}-sccache

      - name: Configure CMake
        run: >
          LDFLAGS="-fuse-ld=lld" cmake
          --preset dev_linux
          -B build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          -DBUILD_TESTING=ON

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Run Tests (Release)
        working-directory: build
        run: ctest --output-on-failure --build-config Release
