# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 firecat2d developers

name: Windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      - name: Setup sccache
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          variant: sccache
          create-symlink: true
          update-package-index: false
          key: ${{ runner.os }}-${{ runner.arch }}-sccache

      - name: Configure CMake
        run: >
          cmake -B build -G "Ninja"
          -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure
